### ISSUE TITLE
Server crash when trying to use NVG

### ISSUE THREAD

**Issue by GitPois1x** [loleq2105/Ag4tr#2]
[latest.log](https://github.com/loleq2105/Ag4tr/files/5890570/latest.log)

**Comment by loleq2105** [comment]
Confirmed. Currently working on it, should slap up a release with some proper toggle code this weekend.

**Comment by Binero** [comment]
@loleq2105 Was this issue fixed? I noticed https://github.com/loleq2105/Ag4tr/pull/3 but I am unsure whether it relates.

**Comment by loleq2105** [comment]
@Binero Oh, it was, but not in the way I wanted, really. I made it so that now you have to shift-rightclick with the NVG in your hand due to the lack of time. I am currently _actually_ working on making it keybind-toggle-based. I'll release your recipe patch with the next version, which will feature the said toggle mechanic. I'll close this issue once everything is the way I wanted it to be.

**Comment by loleq2105** [comment]
This took an unnervingly long time. I shall blame this on school.
Anyway, 592f36c850503cf77915995232d942f195886888
I'll still leave this issue up for a week or so, just to make sure that everything works, as I haven't tested this on servers.

**Comment by loleq2105** [comment]
This took an unnervingly long time. I shall blame it on school.
Anyway, 592f36c
I'll still leave this issue up for a week or so just to make sure that everything works, as I haven't tested this on servers.
